import Image from 'next/image'
import localFont from 'next/font/local'
import './globals.css'

import rotatePhone from '@/assets/svg/rotatephone.svg?url'


const bebas = localFont({
  src: [
    {
      path: '../assets/fonts/BebasNeuePro-Regular.woff2',
      weight: '400',
    },
    {
      path: '../assets/fonts/BebasNeuePro-Bold.woff2',
      weight: '700'
    }
  ],
  variable: '--font-bebas'
})


export const metadata = {
  title: 'Lapetane',
  description: 'Generated by create next app',
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    viewportFit: 'cover'
  },
}


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${bebas.variable}`}>
      <body>
        {children}

        <div className="tablet:hidden landscape:hidden flex-centered flex-col bg-dark fixed inset-0 z-[999]">
          <h3 className="text-2xl font-bold uppercase mt-10">Please rotate your phone</h3>
          <img src={rotatePhone.src} className="w-48" />
        </div>
      </body>
    </html>
  )
}
